name: Android CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'renovate.json'
      - '.editorconfig'
      - '.gitignore'
      - '.github/**'
      - '.github/workflows/**'
      - '.idea/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'renovate.json'
      - '.editorconfig'
      - '.gitignore'
      - '.github/**'
      - '.github/workflows/**'
      - '.idea/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{!startsWith(github.event.head_commit.message, '[skip ci]') && success() && github.ref == 'refs/heads/main'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: .github/*.apk
